export const API = {
    "LOGIN": "/user/login",
    "CARTYPES": "/cartype/list",
    "CREATE_CARTYPE": "/cartype/create",
    "DELETE_CARTYPE": (id: string) => `/cartype/del/${id}`,
    "BRANDS": "/brand/list",
    "CREATE_BRAND": "/brand/create",
    "UPDATE_BRAND": (id: string) => `/brand/update/${id}`,
    "DELETE_BRAND": (id: string) => `/brand/delete/${id}`,
    "PRODUCTS": "/product/get_list",
    "PRODUCT_DETAILS": (id: string) => `/product/get_detail/${id}`,
    "DELETE_PRODUCT": (id: string) => `/product/delete/${id}`,
    "CREATE_PRODUCT": "/product/create",
    "UPDATE_PRODUCT": (id: string) => `/product/update/${id}`,
    "CREATE_BANNER": "/banner/create",
    "UPDATE_BANNER": (id: string) => `/banner/update/${id}`,
    "DELETE_BANNER": (id: string) => `/banner/delete/${id}`,
    "BANNERS": "/banner/getList",
    "NEWS": "/news/listnews",
    "CREATE_NEW": "/news/create",
    "UDPATE_NEW": (id: string) => `/news/upnews/${id}`,
    "CREATE_CONTACT": "/contact/create",
    "IMAGES": "/images/getlist",
    "CREATE_IMAGE": "/images/create",
    "DELETE_IMAGE": (id: string) => `/images/del/${id}`,
    "UPDATE_IMAGE": (id: string) => `/images/update/${id}`
}