export const PATH = {
    NEW_USER: "/cms/users/new",
    CARTYPES: "/cms/cartypes",
    NEW_CARTYPE: "/cms/cartypes/new",
    USERS: "/cms/users",
    PRODUCTS: "/cms/products/list",
    NEW_PRODUCT: "/cms/products/new",
    EDIT_PRODUCT: "/cms/products/edit",
    CONTACT: "/cms/contact",
    LOGIN: "/",
    PROFILE: "/cms/profile",
    DASHBOARD: "/cms/dashboard",
    PAYMENT_METHODS: "/cms/payments/methods",
    BANNERS: "/cms/banners",
    UPLOAD_FILES: "/cms/upload/files",
    BRANDS: "/cms/brands",
    NEW_BRAND: "/cms/brands/new",
    NEW_BANNER: "/cms/banners/new",
    NEW_SHIPPING_ADDRESS: "/cms/shipping/new",
    NEWS: "/cms/news",
    NEW_NEWS: "/cms/news/new",
    IMAGES: "/cms/images",
    NEW_IMAGE: "/cms/images/new"
}