export const PATH = {
    NEW_USER: "/cms/users/new",
    CARTYPES: "/cms/cartypes",
    NEW_CARTYPE: "/cms/cartypes/new",
    USERS: "/cms/users",
    PRODUCTS: "/cms/products/list",
    NEW_PRODUCT: "/cms/products/new",
    EDIT_PRODUCT: "/cms/products/edit",
    SITE_CONFIG: "/cms/config/site",
    LOGIN: "/",
    PROFILE: "/cms/profile",
    DASHBOARD: "/cms/dashboard",
    PAYMENT_METHODS: "/cms/payments/methods",
    BANNERS: "/cms/banners",
    UPLOAD_FILES: "/cms/upload/files",
    BRANDS: "/cms/brands",
    NEW_BRAND: "/cms/brands/new",
    NEW_BANNER: "/cms/banners/new",
    NEW_SHIPPING_ADDRESS: "/cms/shipping/new",
    VOUCHERS: "/cms/vouchers",
    NEW_VOUCHERS: "/cms/vouchers/new"
}