interface Product {
    priority?: number,
    _id?: string,
    name?: string,
    brand?: string,
    brand?: { name?: string },
    carType?: string,
    carType?: { name?: string },
    price?: number,
    color?: string,
    year?: number,
    kmtraveled?: number,
    fuelType?: string,
    transmission?: string,
    engine?: string,
    horsepower?: number,
    images?: string[],
    description?: string,
    numberseats?: number,
    status?: string,
    stock?: number
}